# Generated by Django 4.0.4 on 2022-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Datetime', models.DateTimeField()),
                ('Status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=20)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('ModifiedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
